We know self is a nile-primtype, we need to check if a is a nile-primtype.
Without this fix, the maru compiler will abort when trying
to compile the gezira code extracted from compiler/js/nile-compiler.html

error: selector name has no method for <nile-recordtype>: (<nile-recordtype>)

Which is to be expected. nile-recordtype only has 'fields'.

With this fix, it no longer aborts.